In [1]:
import numpy as np
import pandas as pd 

df = pd.read_csv("Crop_production.csv")
df.head()

,Unnamed: 0,State_Name,Crop_Type,Crop,N,P,K,pH,rainfall,temperature,Area_in_hectares,Production_in_tons,Yield_ton_per_hec
0,0,andhra pradesh,kharif,cotton,120,40,20,5.46,654.34,29.266667,7300.0,9400.0,1.287671
1,1,andhra pradesh,kharif,horsegram,20,60,20,6.18,654.34,29.266667,3300.0,1000.0,0.303030
2,2,andhra pradesh,kharif,jowar,80,40,40,5.42,654.34,29.266667,10100.0,10200.0,1.009901
3,3,andhra pradesh,kharif,maize,80,40,20,5.62,654.34,29.266667,2800.0,4900.0,1.750000
4,4,andhra pradesh,kharif,moong,20,40,20,5.68,654.34,29.266667,1300.0,500.0,0.384615

In [2]:
df.drop(columns = "Unnamed: 0",inplace = True)

In [3]:
df.shape

(99849, 12)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99849 entries, 0 to 99848
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State_Name          99849 non-null  object
 1   Crop_Type           99849 non-null  object
 2   Crop                99849 non-null  object
 3   N                   99849 non-null  int64
 4   P                   99849 non-null  int64
 5   K                   99849 non-null  int64
 6   pH                  99849 non-null  float64
 7   rainfall            99849 non-null  float64
 8   temperature         99849 non-null  float64
 9   Area_in_hectares    99849 non-null  float64
 10  Production_in_tons  99849 non-null  float64
 11  Yield_ton_per_hec   99849 non-null  float64
dtypes: float64(6), int64(3), object(3)
memory usage: 9.1+ MB

In [5]:
df.isnull().sum()

State_Name            0
Crop_Type             0
Crop                  0
N                     0
P                     0
K                     0
pH                    0
rainfall              0
temperature           0
Area_in_hectares      0
Production_in_tons    0
Yield_ton_per_hec     0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
def soil_type(pH):
    if pH < 7:
        return "Acidic"
    elif pH == 7:
        return "Neutral"
    else :
        return "Basic"


df['Soil_type'] = df['pH'].apply(soil_type)
df

,State_Name,Crop_Type,Crop,N,P,K,pH,rainfall,temperature,Area_in_hectares,Production_in_tons,Yield_ton_per_hec,Soil_type
0,andhra pradesh,kharif,cotton,120,40,20,5.46,654.34,29.266667,7300.0,9400.0,1.287671,Acidic
1,andhra pradesh,kharif,horsegram,20,60,20,6.18,654.34,29.266667,3300.0,1000.0,0.303030,Acidic
2,andhra pradesh,kharif,jowar,80,40,40,5.42,654.34,29.266667,10100.0,10200.0,1.009901,Acidic
3,andhra pradesh,kharif,maize,80,40,20,5.62,654.34,29.266667,2800.0,4900.0,1.750000,Acidic
4,andhra pradesh,kharif,moong,20,40,20,5.68,654.34,29.266667,1300.0,500.0,0.384615,Acidic
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99844,west bengal,rabi,wheat,60,30,30,6.70,152.54,22.280000,2013.0,5152.0,2.559364,Acidic
99845,west bengal,summer,maize,80,40,20,5.68,182.50,29.200000,258.0,391.0,1.515504,Acidic
99846,west bengal,summer,rice,80,40,40,5.64,182.50,29.200000,105.0,281.0,2.676190,Acidic
99847,west bengal,rabi,rice,80,40,40,5.42,152.54,22.280000,152676.0,261435.0,1.712352,Acidic
99848,west bengal,rabi,sesamum,30,15,30,6.54,152.54,22.280000,244.0,95.0,0.389344,Acidic

In [8]:
df.describe()

,N,P,K,pH,rainfall,temperature,Area_in_hectares,Production_in_tons,Yield_ton_per_hec
count,99849.000000,99849.000000,99849.000000,99849.000000,99849.000000,99849.000000,99849.000000,9.984900e+04,99849.000000
mean,69.816823,41.593656,42.037827,5.643624,701.151085,26.684154,16476.585668,3.776291e+04,3.931149
std,39.571469,15.056508,28.430263,0.505283,604.701552,4.851214,43604.268231,1.222447e+05,33.872242
min,10.000000,10.000000,10.000000,3.820000,3.274569,1.180000,0.580000,0.000000e+00,0.000000
25%,50.000000,40.000000,20.000000,5.360000,157.310000,23.106000,130.000000,1.620000e+02,0.586207
50%,75.000000,40.000000,30.000000,5.540000,579.750000,27.333333,1010.000000,1.506000e+03,1.329268
75%,80.000000,60.000000,50.000000,5.960000,1110.780000,29.266667,8099.000000,1.439500e+04,2.997288
max,180.000000,125.000000,200.000000,7.000000,3322.060000,35.346667,726300.000000,3.530571e+06,9801.000000

In [9]:
print((df['Production_in_tons'] == 0).sum())
print((df['Yield_ton_per_hec'] == 0).sum())
print((df['Area_in_hectares'] == 0).sum())

1412
1412
0

In [10]:
def rainfall_level(rainfall):
    if rainfall <= 157:
        return "Low"
    elif rainfall<= 580:
        return "Moderate"
    elif rainfall <= 1111:
        return "High"
    else : 
        return "Very High"


df['Rainfall_level'] = df['rainfall'].apply(rainfall_level)

df['Rainfall_level'].value_counts()

Rainfall_level
Moderate     26125
High         25134
Very High    24398
Low          24192
Name: count, dtype: int64

In [11]:
def temperature_level(temperature):
   if temperature <= 23.1:
       return "Low"
   elif temperature <= 27.3:
       return "Moderate"
   elif temperature <= 29.3:
       return "High"
   else:
       return "Very High"


df['Temperature_level'] = df['temperature'].apply(temperature_level)

df['Temperature_level'].value_counts()

Temperature_level
High         26543
Low          24841
Moderate     24563
Very High    23902
Name: count, dtype: int64

In [12]:
df.to_csv("Crop_production_cleaned.csv",index = False)

In [13]:
production_by_state = df.groupby('State_Name')['Production_in_tons'].sum().sort_values(ascending=False)
production_by_state

State_Name
uttar pradesh                  7.020635e+08
west bengal                    4.439035e+08
punjab                         3.733294e+08
madhya pradesh                 2.486210e+08
haryana                        2.119462e+08
tamil nadu                     2.089889e+08
rajasthan                      1.955060e+08
maharashtra                    1.895290e+08
gujarat                        1.882133e+08
bihar                          1.788725e+08
karnataka                      1.776310e+08
andhra pradesh                 1.584045e+08
telangana                      1.129862e+08
odisha                         9.020717e+07
assam                          8.285917e+07
chhattisgarh                   5.730316e+07
kerala                         5.441159e+07
uttarakhand                    2.006152e+07
himachal pradesh               1.709964e+07
jammu and kashmir              1.183137e+07
jharkhand                      1.041770e+07
tripura                        8.444565e+06
meghalaya                      7.648602e+06
nagaland                       6.391881e+06
manipur                        4.850028e+06
arunachal pradesh              3.271814e+06
sikkim                         1.442402e+06
mizoram                        1.426322e+06
goa                            1.044197e+06
puducherry                     1.038175e+06
dadra and nagar haveli         4.055220e+05
andaman and nicobar islands    3.844167e+05
chandigarh                     5.481100e+04
Name: Production_in_tons, dtype: float64

In [14]:
production_by_crop = df.groupby('Crop')['Production_in_tons'].sum().sort_values(ascending=False)
production_by_crop

Crop
rice           1.188908e+09
wheat          1.034658e+09
potato         3.153034e+08
cotton         2.158635e+08
maize          1.958153e+08
jute           1.395456e+08
banana         1.183549e+08
soyabean       1.050098e+08
jowar          9.494299e+07
tapioca        8.708139e+07
rapeseed       7.939577e+07
onion          5.637023e+07
ragi           2.799421e+07
barley         1.872960e+07
moong          1.474894e+07
sunflower      1.148408e+07
arecanut       1.139215e+07
sesamum        8.743266e+06
turmeric       7.442136e+06
garlic         6.394675e+06
sweetpotato    6.280208e+06
mango          5.882123e+06
coriander      3.423272e+06
horsegram      3.421522e+06
tomato         2.379203e+06
cashewnuts     1.884503e+06
grapes         1.728423e+06
papaya         1.646858e+06
orange         1.594989e+06
blackpepper    1.256464e+06
pineapple      1.015114e+06
brinjal        8.803830e+05
ladyfinger     3.161870e+05
cabbage        2.391190e+05
coffee         1.300120e+05
cardamom       1.202057e+05
jackfruit      5.926600e+04
drumstick      4.615300e+04
blackgram      4.165900e+04
ginger         3.866900e+04
cauliflower    1.843300e+04
carrot         4.066000e+03
radish         3.687000e+03
bottlegourd    5.260000e+02
bittergourd    2.970000e+02
cucumber       0.000000e+00
beetroot       0.000000e+00
apple          0.000000e+00
ashgourd       0.000000e+00
pomegranate    0.000000e+00
pumpkin        0.000000e+00
ridgegourd     0.000000e+00
watermelon     0.000000e+00
Name: Production_in_tons, dtype: float64

In [15]:
production_by_crop_type = df.groupby('Crop_Type')['Production_in_tons'].sum().sort_values(ascending=False)
production_by_crop_type

Crop_Type
rabi          1.666739e+09
kharif        1.463302e+09
whole year    5.313110e+08
summer        1.092364e+08
Name: Production_in_tons, dtype: float64

In [16]:
yield_by_state = df.groupby('State_Name')['Yield_ton_per_hec'].mean().sort_values(ascending = False)
yield_by_state

State_Name
chandigarh                     9.572729
tamil nadu                     8.940241
gujarat                        7.688684
puducherry                     6.651801
haryana                        6.070588
manipur                        5.115117
kerala                         4.872155
andhra pradesh                 4.855497
uttar pradesh                  4.652979
telangana                      4.157090
maharashtra                    3.870797
west bengal                    3.700550
chhattisgarh                   3.603305
andaman and nicobar islands    3.483818
meghalaya                      3.434204
assam                          3.362933
madhya pradesh                 3.245402
uttarakhand                    3.230566
bihar                          3.164731
karnataka                      3.079276
punjab                         2.970001
nagaland                       2.821667
arunachal pradesh              2.745340
jharkhand                      2.737534
dadra and nagar haveli         2.675697
tripura                        2.656486
himachal pradesh               2.247606
mizoram                        2.148227
jammu and kashmir              2.001128
odisha                         1.915904
rajasthan                      1.908562
sikkim                         1.565364
goa                            1.419721
Name: Yield_ton_per_hec, dtype: float64

In [17]:
yield_by_crop = df.groupby('Crop')['Yield_ton_per_hec'].mean().sort_values(ascending = False)
yield_by_crop

Crop
banana         26.207587
papaya         26.016393
grapes         19.936165
tapioca        19.362005
cashewnuts     13.862270
potato         12.759288
pineapple      12.385601
onion          11.384912
cabbage         9.937189
jute            9.388225
ginger          8.694952
sweetpotato     8.458100
orange          7.588394
jackfruit       6.178924
brinjal         5.576893
tomato          5.271317
carrot          4.764793
mango           3.431836
radish          3.338958
ladyfinger      3.229564
garlic          3.181640
turmeric        2.762696
maize           2.695810
cotton          2.224884
wheat           2.037195
rice            1.919871
arecanut        1.846207
barley          1.746630
cauliflower     1.453605
bottlegourd     1.207976
ragi            1.170437
soyabean        1.028520
blackpepper     1.009993
jowar           1.002517
sunflower       0.935844
rapeseed        0.753098
coffee          0.708808
blackgram       0.681632
bittergourd     0.595745
coriander       0.489085
horsegram       0.433422
moong           0.425035
drumstick       0.422254
sesamum         0.371752
cardamom        0.143598
cucumber        0.000000
beetroot        0.000000
apple           0.000000
ashgourd        0.000000
pomegranate     0.000000
pumpkin         0.000000
ridgegourd      0.000000
watermelon      0.000000
Name: Yield_ton_per_hec, dtype: float64

In [18]:
yield_by_crop_type = df.groupby('Crop_Type')['Yield_ton_per_hec'].mean().sort_values(ascending = False)
yield_by_crop_type

Crop_Type
whole year    8.684194
rabi          2.608710
summer        2.563535
kharif        1.878011
Name: Yield_ton_per_hec, dtype: float64

In [19]:
area_per_state = df.groupby('State_Name')['Area_in_hectares'].sum().sort_values(ascending = False)
area_per_state

State_Name
uttar pradesh                  2.469603e+08
madhya pradesh                 1.901744e+08
maharashtra                    1.686711e+08
rajasthan                      1.297580e+08
west bengal                    1.080396e+08
karnataka                      1.054240e+08
punjab                         9.473650e+07
bihar                          9.085666e+07
gujarat                        6.954940e+07
odisha                         6.639470e+07
haryana                        6.458052e+07
andhra pradesh                 5.645474e+07
telangana                      5.004586e+07
chhattisgarh                   4.712148e+07
tamil nadu                     4.703934e+07
assam                          4.378689e+07
kerala                         1.217118e+07
uttarakhand                    9.840034e+06
himachal pradesh               9.561018e+06
jharkhand                      9.133951e+06
jammu and kashmir              7.857231e+06
nagaland                       3.741685e+06
tripura                        3.380805e+06
meghalaya                      2.680408e+06
arunachal pradesh              2.385509e+06
manipur                        1.796207e+06
mizoram                        9.082703e+05
sikkim                         8.206120e+05
goa                            6.022840e+05
puducherry                     3.405790e+05
dadra and nagar haveli         2.102420e+05
andaman and nicobar islands    1.364186e+05
chandigarh                     1.062800e+04
Name: Area_in_hectares, dtype: float64

In [20]:
area_per_crop = df.groupby('Crop')['Area_in_hectares'].sum().sort_values(ascending = False)
area_per_crop

Crop
rice           5.728720e+08
wheat          3.759551e+08
cotton         1.189112e+08
jowar          1.162422e+08
soyabean       1.014770e+08
maize          9.528422e+07
rapeseed       7.603504e+07
moong          4.070291e+07
sesamum        2.330036e+07
sunflower      2.142874e+07
ragi           2.026436e+07
potato         1.712247e+07
jute           1.164635e+07
barley         8.990947e+06
horsegram      8.484606e+06
onion          5.020571e+06
coriander      4.715509e+06
arecanut       4.410533e+06
banana         4.239542e+06
cashewnuts     4.077835e+06
blackpepper    2.969130e+06
tapioca        2.955641e+06
turmeric       2.198714e+06
mango          1.460571e+06
garlic         1.395610e+06
cardamom       7.939719e+05
sweetpotato    7.790433e+05
tomato         3.318360e+05
jackfruit      1.914710e+05
coffee         1.679080e+05
orange         1.422650e+05
brinjal        1.102850e+05
pineapple      9.259000e+04
papaya         6.868400e+04
grapes         6.596100e+04
ladyfinger     6.524500e+04
blackgram      6.483900e+04
drumstick      5.409000e+04
cabbage        1.540600e+04
cauliflower    1.526500e+04
cucumber       1.229700e+04
watermelon     1.211900e+04
bittergourd    5.940000e+03
carrot         4.872000e+03
ginger         4.554000e+03
bottlegourd    2.524000e+03
radish         1.806000e+03
pumpkin        1.767000e+03
beetroot       1.570000e+03
ashgourd       1.561000e+03
pomegranate    1.031000e+03
ridgegourd     6.160000e+02
apple          8.000000e+00
Name: Area_in_hectares, dtype: float64

In [21]:
# -------------------------------
# WEATHER ANALYSIS
# -------------------------------

print("="*60)
print("RAINFALL vs PRODUCTION")
print(df['rainfall'].corr(df['Production_in_tons']))
print()

print("="*60)
print("RAINFALL vs YIELD")
print(df['rainfall'].corr(df['Yield_ton_per_hec']))
print()

print("="*60)
print("TEMPERATURE vs PRODUCTION")
print(df['temperature'].corr(df['Production_in_tons']))
print()

print("="*60)
print("TEMPERATURE vs YIELD")
print(df['temperature'].corr(df['Yield_ton_per_hec']))
print()

print("="*60)
print("PRODUCTION BY RAINFALL LEVEL")
print(df.groupby('Rainfall_level')['Production_in_tons'].mean().sort_values(ascending=False))
print()

print("="*60)
print("YIELD BY RAINFALL LEVEL")
print(df.groupby('Rainfall_level')['Yield_ton_per_hec'].mean().sort_values(ascending=False))
print()

print("="*60)
print("PRODUCTION BY TEMPERATURE LEVEL")
print(df.groupby('Temperature_level')['Production_in_tons'].mean().sort_values(ascending=False))
print()

print("="*60)
print("YIELD BY TEMPERATURE LEVEL")
print(df.groupby('Temperature_level')['Yield_ton_per_hec'].mean().sort_values(ascending=False))

============================================================
RAINFALL vs PRODUCTION
-0.09794774055021849

============================================================
RAINFALL vs YIELD
0.02649170085206552

============================================================
TEMPERATURE vs PRODUCTION
-0.02319900724833932

============================================================
TEMPERATURE vs YIELD
0.0021762810366059587

============================================================
PRODUCTION BY RAINFALL LEVEL
Rainfall_level
Low          63278.476925
High         34216.574969
Moderate     31455.616625
Very High    22869.854695
Name: Production_in_tons, dtype: float64

============================================================
YIELD BY RAINFALL LEVEL
Rainfall_level
High         6.149734
Very High    4.373803
Low          2.772570
Moderate     2.456187
Name: Yield_ton_per_hec, dtype: float64

============================================================
PRODUCTION BY TEMPERATURE LEVEL
Temperature_level
Low          56036.181244
Very High    36113.406627
Moderate     29692.945317
High         29614.729644
Name: Production_in_tons, dtype: float64

============================================================
YIELD BY TEMPERATURE LEVEL
Temperature_level
High         6.464895
Moderate     3.417094
Low          3.235700
Very High    2.368485
Name: Yield_ton_per_hec, dtype: float64

In [22]:
# -------------------------------
# SOIL ANALYSIS
# -------------------------------

print("="*60)
print("SOIL TYPE vs PRODUCTION")
print(df.groupby('Soil_type')['Production_in_tons'].mean().sort_values(ascending=False))
print()

print("="*60)
print("SOIL TYPE vs YIELD")
print(df.groupby('Soil_type')['Yield_ton_per_hec'].mean().sort_values(ascending=False))
print()

print("="*60)
print("pH vs PRODUCTION")
print(df['pH'].corr(df['Production_in_tons']))
print()

print("="*60)
print("pH vs YIELD")
print(df['pH'].corr(df['Yield_ton_per_hec']))
print()

print("="*60)
print("N vs PRODUCTION")
print(df['N'].corr(df['Production_in_tons']))
print()

print("="*60)
print("N vs YIELD")
print(df['N'].corr(df['Yield_ton_per_hec']))
print()

print("="*60)
print("P vs PRODUCTION")
print(df['P'].corr(df['Production_in_tons']))
print()

print("="*60)
print("P vs YIELD")
print(df['P'].corr(df['Yield_ton_per_hec']))
print()

print("="*60)
print("K vs PRODUCTION")
print(df['K'].corr(df['Production_in_tons']))
print()

print("="*60)
print("K vs YIELD")
print(df['K'].corr(df['Yield_ton_per_hec']))

============================================================
SOIL TYPE vs PRODUCTION
Soil_type
Neutral    173907.028703
Acidic      37001.939768
Name: Production_in_tons, dtype: float64

============================================================
SOIL TYPE vs YIELD
Soil_type
Acidic     3.941708
Neutral    2.042206
Name: Yield_ton_per_hec, dtype: float64

============================================================
pH vs PRODUCTION
0.0736541714510994

============================================================
pH vs YIELD
0.0064273785816376236

============================================================
N vs PRODUCTION
0.09788833146675475

============================================================
N vs YIELD
0.09022286552635315

============================================================
P vs PRODUCTION
-0.010697861601572697

============================================================
P vs YIELD
0.07680552857027491

============================================================
K vs PRODUCTION
-0.026378692315398564

============================================================
K vs YIELD
0.07619791335773535

In [23]:
# -------------------------------
# COMBINED ANALYSIS
# -------------------------------

print("="*60)
print("STATE x CROP -> PRODUCTION")
print(df.groupby(['State_Name','Crop'])['Production_in_tons'].sum().sort_values(ascending=False).head(20))
print()

print("="*60)
print("STATE x CROP -> YIELD")
print(df.groupby(['State_Name','Crop'])['Yield_ton_per_hec'].mean().sort_values(ascending=False).head(20))
print()

print("="*60)
print("STATE x CROP TYPE -> PRODUCTION")
print(df.groupby(['State_Name','Crop_Type'])['Production_in_tons'].sum().sort_values(ascending=False))
print()

print("="*60)
print("STATE x CROP TYPE -> YIELD")
print(df.groupby(['State_Name','Crop_Type'])['Yield_ton_per_hec'].mean().sort_values(ascending=False))

============================================================
STATE x CROP -> PRODUCTION
State_Name      Crop
uttar pradesh   wheat       355139389.0
punjab          wheat       208528000.0
west bengal     rice        197236283.0
uttar pradesh   rice        162401886.0
                potato      141332108.0
punjab          rice        135094000.0
haryana         wheat       134411000.0
west bengal     jute        113458868.0
                potato      110675274.0
andhra pradesh  rice        104230833.0
madhya pradesh  wheat       100383572.0
rajasthan       wheat        94669124.0
tamil nadu      rice         81498480.0
odisha          rice         79894742.0
gujarat         cotton       70452000.0
madhya pradesh  soyabean     65667165.0
bihar           rice         60571177.0
                wheat        58610101.0
telangana       rice         52921987.0
chhattisgarh    rice         52268917.0
Name: Production_in_tons, dtype: float64

============================================================
STATE x CROP -> YIELD
State_Name      Crop
telangana       papaya        110.609950
andhra pradesh  papaya        109.019456
gujarat         banana         63.011881
tamil nadu      cabbage        60.173617
maharashtra     banana         57.567999
tamil nadu      banana         41.090617
chhattisgarh    banana         40.653276
uttar pradesh   banana         38.680774
chhattisgarh    papaya         38.101787
tamil nadu      tapioca        37.621505
                cashewnuts     35.544314
haryana         onion          34.023658
madhya pradesh  papaya         33.392941
                banana         30.426691
tamil nadu      pineapple      29.726917
karnataka       grapes         28.921437
kerala          tapioca        27.746996
gujarat         onion          27.575229
puducherry      banana         24.754589
andhra pradesh  banana         24.734713
Name: Yield_ton_per_hec, dtype: float64

============================================================
STATE x CROP TYPE -> PRODUCTION
State_Name                   Crop_Type
uttar pradesh                rabi          4.513601e+08
punjab                       rabi          2.092297e+08
west bengal                  rabi          1.857917e+08
uttar pradesh                kharif        1.842285e+08
punjab                       kharif        1.631310e+08
                                               ...
chandigarh                   whole year    1.359400e+04
jharkhand                    whole year    9.196870e+03
andaman and nicobar islands  rabi          8.580520e+03
chandigarh                   kharif        6.703000e+03
tamil nadu                   rabi          9.001000e+02
Name: Production_in_tons, Length: 111, dtype: float64

============================================================
STATE x CROP TYPE -> YIELD
State_Name    Crop_Type
gujarat       whole year    27.393109
maharashtra   whole year    26.045955
haryana       whole year    22.271201
chandigarh    whole year    19.775463
tripura       whole year    17.733842
                              ...
chhattisgarh  rabi           0.877063
              kharif         0.825866
rajasthan     kharif         0.805349
goa           whole year     0.403929
tamil nadu    rabi           0.258315
Name: Yield_ton_per_hec, Length: 111, dtype: float64

In [24]:
# -------------------------------
# CORRELATION MATRIX
# -------------------------------

corr_matrix = df[['N','P','K','pH',
                  'rainfall','temperature',
                  'Area_in_hectares',
                  'Production_in_tons',
                  'Yield_ton_per_hec']].corr()

print(corr_matrix)

                           N         P         K        pH  rainfall  \
N                   1.000000  0.342521  0.486650 -0.235437  0.111900
P                   0.342521  1.000000  0.210349 -0.254776  0.110686
K                   0.486650  0.210349  1.000000 -0.246708  0.369173
pH                 -0.235437 -0.254776 -0.246708  1.000000 -0.021997
rainfall            0.111900  0.110686  0.369173 -0.021997  1.000000
temperature        -0.044755 -0.056988 -0.078606  0.012203  0.034479
Area_in_hectares    0.009287 -0.057514 -0.120388  0.060136 -0.135261
Production_in_tons  0.097888 -0.010698 -0.026379  0.073654 -0.097948
Yield_ton_per_hec   0.090223  0.076806  0.076198  0.006427  0.026492

                    temperature  Area_in_hectares  Production_in_tons  \
N                     -0.044755          0.009287            0.097888
P                     -0.056988         -0.057514           -0.010698
K                     -0.078606         -0.120388           -0.026379
pH                     0.012203          0.060136            0.073654
rainfall               0.034479         -0.135261           -0.097948
temperature            1.000000         -0.012948           -0.023199
Area_in_hectares      -0.012948          1.000000            0.736019
Production_in_tons    -0.023199          0.736019            1.000000
Yield_ton_per_hec      0.002176         -0.018287            0.028306

                    Yield_ton_per_hec
N                            0.090223
P                            0.076806
K                            0.076198
pH                           0.006427
rainfall                     0.026492
temperature                  0.002176
Area_in_hectares            -0.018287
Production_in_tons           0.028306
Yield_ton_per_hec            1.000000